; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "ASI-OS"
#define MyAppVersion "0.2.0"
#define MyAppPublisher "Cloudhabil contributors"
#define MyAppURL "cloudhabil.com"
#define MyAppExeName "ASI-OS.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".cliai"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{FDEE7DE9-5E36-4737-86F3-B3ECE14B6B5B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\LICENSE
InfoBeforeFile=C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\docs\pre_install.md
InfoAfterFile=C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\docs\post_install.md
PrivilegesRequiredOverridesAllowed=commandline
OutputDir=C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\dist
OutputBaseFilename=ASI-OS_Installer_v0.2.0
SolidCompression=yes
WizardStyle=modern dynamic windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\dist\ASI-OS\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
;Registry data from file cli-ai-registry.reg
Root: HKLM; Subkey: "SOFTWARE\CLI-AI"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI"; ValueType: string; ValueName: "DisplayName"; ValueData: "CLI AI"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI"; ValueType: string; ValueName: "Version"; ValueData: "0.1.0"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI"; ValueType: string; ValueName: "Publisher"; ValueData: "CLI AI Contributors"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI"; ValueType: string; ValueName: "InstallLocation"; ValueData: "C:\Users\usuario\Business\CLI_A1_GHR\CLI-main"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI"; ValueType: string; ValueName: "InstallDate"; ValueData: "20251229"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI"; ValueType: string; ValueName: "HelpLink"; ValueData: "https://github.com/your-repo/cli-ai"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI"; ValueType: string; ValueName: "URLInfoAbout"; ValueData: "https://github.com/your-repo/cli-ai"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Settings"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Settings"; ValueType: string; ValueName: "DataDirectory"; ValueData: "C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\data"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Settings"; ValueType: string; ValueName: "ConfigDirectory"; ValueData: "C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\configs"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Settings"; ValueType: string; ValueName: "LogDirectory"; ValueData: "C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\logs"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Settings"; ValueType: string; ValueName: "PromptDirectory"; ValueData: "C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\prompts"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Database"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Database"; ValueType: string; ValueName: "KnowledgeBasePath"; ValueData: "C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\data\kb.db"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Database"; ValueType: string; ValueName: "HierarchicalMemoryPath"; ValueData: "C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\data\hier_mem"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Database"; ValueType: string; ValueName: "JournalMode"; ValueData: "WAL"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Server"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Server"; ValueType: dword; ValueName: "BusServerPort"; ValueData: $00001bb8; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Server"; ValueType: string; ValueName: "BusServerHost"; ValueData: "127.0.0.1"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Server"; ValueType: string; ValueName: "RedisURL"; ValueData: "redis://localhost:6379/0"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Server"; ValueType: dword; ValueName: "AgentPortStart"; ValueData: $00001b59; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Server"; ValueType: dword; ValueName: "AgentPortEnd"; ValueData: $00001b61; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Models"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Models"; ValueType: string; ValueName: "RouterBaseURL"; ValueData: "http://localhost:11434/v1"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Models"; ValueType: string; ValueName: "RouterModel"; ValueData: "qwen2:latest"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Models"; ValueType: string; ValueName: "QwenBaseURL"; ValueData: "http://localhost:11434/v1"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Models"; ValueType: string; ValueName: "QwenModel"; ValueData: "qwen2:latest"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Models"; ValueType: string; ValueName: "DeepSeekBaseURL"; ValueData: "http://localhost:11434/v1"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Models"; ValueType: string; ValueName: "DeepSeekModel"; ValueData: "codegemma:latest"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Features"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Features"; ValueType: dword; ValueName: "UseOpenVINO"; ValueData: $00000000; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Features"; ValueType: dword; ValueName: "UseFAISS"; ValueData: $00000000; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Features"; ValueType: dword; ValueName: "EnableObservability"; ValueData: $00000000; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Features"; ValueType: dword; ValueName: "EnableTokenCounter"; ValueData: $00000000; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKCU; Subkey: "Software\CLI-AI"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "Software\CLI-AI"; ValueType: dword; ValueName: "FirstRun"; ValueData: $00000001; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "Software\CLI-AI"; ValueType: string; ValueName: "LastUsed"; ValueData: ""; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "Software\CLI-AI"; ValueType: string; ValueName: "UserDataPath"; ValueData: "%APPDATA%\CLI-AI"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "Software\CLI-AI\Preferences"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "Software\CLI-AI\Preferences"; ValueType: dword; ValueName: "EnableLogging"; ValueData: $00000001; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "Software\CLI-AI\Preferences"; ValueType: string; ValueName: "LogLevel"; ValueData: "INFO"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "Software\CLI-AI\Preferences"; ValueType: dword; ValueName: "AutoUpdate"; ValueData: $00000000; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "Software\CLI-AI\Preferences"; ValueType: dword; ValueName: "TelemetryEnabled"; ValueData: $00000000; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "CLI_AI_HOME"; ValueData: "C:\Users\usuario\Business\CLI_A1_GHR\CLI-main"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "CLI_AI_VERSION"; ValueData: "0.1.0"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKA; Subkey: "Software\Classes\.cliai"; Flags: uninsdeletekeyifempty
Root: HKA; Subkey: "Software\Classes\.cliai"; ValueType: string; ValueName: ""; ValueData: "CLI.AI.Workflow"; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\.cliai"; ValueType: string; ValueName: "Content Type"; ValueData: "application/x-cli-ai-workflow"; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\CLI.AI.Workflow"; Flags: uninsdeletekeyifempty
Root: HKA; Subkey: "Software\Classes\CLI.AI.Workflow"; ValueType: string; ValueName: ""; ValueData: "CLI AI Workflow File"; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\CLI.AI.Workflow\DefaultIcon"; Flags: uninsdeletekeyifempty
Root: HKA; Subkey: "Software\Classes\CLI.AI.Workflow\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\assets\icon.ico,0"; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\CLI.AI.Workflow\shell\open\command"; Flags: uninsdeletekeyifempty
Root: HKA; Subkey: "Software\Classes\CLI.AI.Workflow\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "\""C:\Python311\python.exe\"" \""C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\ch_cli.py\"" \""%1\"""; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CLI-AI"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CLI-AI"; ValueType: string; ValueName: "DisplayName"; ValueData: "CLI AI - Multi-Agent Command-Line Interface"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CLI-AI"; ValueType: string; ValueName: "DisplayVersion"; ValueData: "0.1.0"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CLI-AI"; ValueType: string; ValueName: "Publisher"; ValueData: "CLI AI Contributors"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CLI-AI"; ValueType: string; ValueName: "InstallLocation"; ValueData: "C:\Users\usuario\Business\CLI_A1_GHR\CLI-main"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CLI-AI"; ValueType: string; ValueName: "DisplayIcon"; ValueData: "C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\assets\icon.ico"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CLI-AI"; ValueType: string; ValueName: "UninstallString"; ValueData: "\""C:\Python311\python.exe\"" \""C:\Users\usuario\Business\CLI_A1_GHR\CLI-main\uninstall.py\"""; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CLI-AI"; ValueType: string; ValueName: "URLInfoAbout"; ValueData: "https://github.com/your-repo/cli-ai"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CLI-AI"; ValueType: string; ValueName: "HelpLink"; ValueData: "https://github.com/your-repo/cli-ai/issues"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CLI-AI"; ValueType: dword; ValueName: "NoModify"; ValueData: $00000001; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CLI-AI"; ValueType: dword; ValueName: "NoRepair"; ValueData: $00000001; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\CLI-AI"; ValueType: dword; ValueName: "EstimatedSize"; ValueData: $000c3500; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Capabilities"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Capabilities"; ValueType: string; ValueName: "ApplicationName"; ValueData: "CLI AI"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Capabilities"; ValueType: string; ValueName: "ApplicationDescription"; ValueData: "Multi-Agent Command-Line Interface for intelligent task orchestration"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Capabilities\FileAssociations"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Capabilities\FileAssociations"; ValueType: string; ValueName: ".cliai"; ValueData: "CLI.AI.Workflow"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Performance"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Performance"; ValueType: dword; ValueName: "MaxWorkers"; ValueData: $00000004; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Performance"; ValueType: dword; ValueName: "ChunkSize"; ValueData: $00000320; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Performance"; ValueType: dword; ValueName: "ChunkOverlap"; ValueData: $00000050; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Performance"; ValueType: dword; ValueName: "MaxTokenBudget"; ValueData: $00002000; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Security"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Security"; ValueType: dword; ValueName: "RequireBusToken"; ValueData: $00000001; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Security"; ValueType: dword; ValueName: "ValidateCertificates"; ValueData: $00000001; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\CLI-AI\Security"; ValueType: dword; ValueName: "AllowExternalConnections"; ValueData: $00000000; Flags: uninsdeletevalue; Check: IsAdminInstallMode
;End of registry data from file cli-ai-registry.reg

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

